name = "love-pixels"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = "dist"

[build.upload]
format = "service-worker"

[site]
bucket = "dist"

[env.production]
name = "love-pixels-production"
route = "love-pixels.pages.dev/*"

[pages]
build_output_dir = "dist"
pages_build_output_dir = "dist" 